project:
  components: "angular/componentes"
  css_extension: "sass"
  directives: "angular/directivas"
  html_extension: "pug"
  pipes: "angular/pipes"
  root: "app.dart"
  routes: "angular/rutas"
  services: "angular/servicios"
